services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - red_cuenca

  productor:
    build: ./sensores       # <--- AQUÍ ESTÁ EL CAMBIO: Construye desde la carpeta
    container_name: productor_sensores
    volumes:
      - ./sensores:/app     # Mantenemos esto para que si editas código, se actualice sin reconstruir
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - red_cuenca

  procesador:
    build: ./consumidores   # <--- AQUÍ ESTÁ EL CAMBIO
    container_name: procesador_alertas
    volumes:
      - ./consumidores:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - red_cuenca

networks:
  red_cuenca:
    driver: bridge
